name: Jack Mawbey Photography
favicon: null
layout_spectrum: 0.99427
typography_spectrum: 0.06604645936749876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d19fde'
    - '#6f4bad'
    - '#ba6a9f'
    - '#f7e8fb'
  brandStrength: 0.9198325343895704
  lightness: 0.07789264060556889
  saturation: 0.75
  rhythmicContrast: 0.39904485223814845
purpose: []
